// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hoteru_be.Context;

namespace hoteru_be.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231127193622_sdfsdfasd")]
    partial class sdfsdfasd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hoteru_be.Entities.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAddress");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("hoteru_be.Entities.Bill", b =>
                {
                    b.Property<int>("IdBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creating")
                        .HasColumnType("datetime2");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("IdBill");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("hoteru_be.Entities.Deposit", b =>
                {
                    b.Property<int>("IdDeposit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDepositType")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("IdDeposit");

                    b.HasIndex("IdDepositType");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("hoteru_be.Entities.DepositType", b =>
                {
                    b.Property<int>("IdDepositType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepositType");

                    b.ToTable("DepositTypes");

                    b.HasData(
                        new
                        {
                            IdDepositType = 1,
                            Title = "Card"
                        },
                        new
                        {
                            IdDepositType = 2,
                            Title = "Cash"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Guest", b =>
                {
                    b.Property<int>("IdGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGuestStatus")
                        .HasColumnType("int");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGuest");

                    b.HasIndex("IdGuestStatus");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestReservation", b =>
                {
                    b.Property<int>("IdGuestReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGuest")
                        .HasColumnType("int");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.HasKey("IdGuestReservation");

                    b.HasIndex("IdGuest");

                    b.HasIndex("IdReservation");

                    b.ToTable("GuestReservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestStatus", b =>
                {
                    b.Property<int>("IdGuestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGuestStatus");

                    b.ToTable("GuestStatuses");
                });

            modelBuilder.Entity("hoteru_be.Entities.Hotel", b =>
                {
                    b.Property<int>("IdHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAddress")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHotel");

                    b.HasIndex("IdAddress")
                        .IsUnique();

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("hoteru_be.Entities.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdHotel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.HasIndex("IdHotel");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("hoteru_be.Entities.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("IdBill")
                        .HasColumnType("int");

                    b.Property<int>("IdDeposit")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Out")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdBill")
                        .IsUnique()
                        .HasFilter("[IdBill] IS NOT NULL");

                    b.HasIndex("IdDeposit")
                        .IsUnique();

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdUser");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.ReservationService", b =>
                {
                    b.Property<int>("IdReservationService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.HasKey("IdReservationService");

                    b.HasIndex("IdReservation");

                    b.HasIndex("IdService");

                    b.ToTable("ReservationService");
                });

            modelBuilder.Entity("hoteru_be.Entities.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("IdRoomStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdRoomType")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("IdRoom");

                    b.HasIndex("IdRoomStatus");

                    b.HasIndex("IdRoomType");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            IdRoom = 1,
                            Capacity = 1,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 2,
                            Capacity = 2,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 3,
                            Capacity = 3,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 4,
                            Capacity = 4,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 5,
                            Capacity = 5,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 6,
                            Capacity = 6,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 7,
                            Capacity = 7,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 8,
                            Capacity = 8,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 9,
                            Capacity = 9,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 10,
                            Capacity = 10,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 11,
                            Capacity = 11,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 12,
                            Capacity = 12,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 13,
                            Capacity = 13,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 14,
                            Capacity = 14,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 15,
                            Capacity = 15,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 16,
                            Capacity = 16,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 17,
                            Capacity = 17,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 18,
                            Capacity = 18,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 19,
                            Capacity = 19,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 20,
                            Capacity = 20,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 21,
                            Capacity = 21,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 22,
                            Capacity = 22,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 23,
                            Capacity = 23,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 24,
                            Capacity = 24,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 25,
                            Capacity = 25,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 26,
                            Capacity = 26,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 27,
                            Capacity = 27,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 28,
                            Capacity = 28,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 29,
                            Capacity = 29,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 30,
                            Capacity = 30,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 31,
                            Capacity = 31,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 32,
                            Capacity = 32,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 33,
                            Capacity = 33,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 34,
                            Capacity = 34,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "305",
                            Price = 3.5f
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomStatus", b =>
                {
                    b.Property<int>("IdRoomStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoomStatus");

                    b.ToTable("RoomStatuses");

                    b.HasData(
                        new
                        {
                            IdRoomStatus = 1,
                            Title = "Out of service"
                        },
                        new
                        {
                            IdRoomStatus = 2,
                            Title = "Occupied"
                        },
                        new
                        {
                            IdRoomStatus = 3,
                            Title = "Ready"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomType", b =>
                {
                    b.Property<int>("IdRoomType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoomType");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            IdRoomType = 1,
                            Title = "Regular"
                        },
                        new
                        {
                            IdRoomType = 2,
                            Title = "Luxury"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdService");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            IdService = 1,
                            Description = "None",
                            Sum = 355.5f,
                            Title = "Breakfast"
                        },
                        new
                        {
                            IdService = 2,
                            Description = "None",
                            Sum = 120.5f,
                            Title = "Spa"
                        },
                        new
                        {
                            IdService = 3,
                            Description = "None",
                            Sum = 248.5f,
                            Title = "Assistent"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.User", b =>
                {
                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdUserType")
                        .HasColumnType("int");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.HasIndex("IdUserType");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("hoteru_be.Entities.UserType", b =>
                {
                    b.Property<int>("IdUserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUserType");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            IdUserType = 1,
                            Title = "Superadmin"
                        },
                        new
                        {
                            IdUserType = 2,
                            Title = "Admin"
                        },
                        new
                        {
                            IdUserType = 3,
                            Title = "Employee"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Deposit", b =>
                {
                    b.HasOne("hoteru_be.Entities.DepositType", "DepositType")
                        .WithMany("Deposits")
                        .HasForeignKey("IdDepositType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepositType");
                });

            modelBuilder.Entity("hoteru_be.Entities.Guest", b =>
                {
                    b.HasOne("hoteru_be.Entities.GuestStatus", "GuestStatus")
                        .WithMany("Guests")
                        .HasForeignKey("IdGuestStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestStatus");
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestReservation", b =>
                {
                    b.HasOne("hoteru_be.Entities.Guest", "Guest")
                        .WithMany("GuestReservations")
                        .HasForeignKey("IdGuest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.Reservation", "Reservation")
                        .WithMany("GuestReservations")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("hoteru_be.Entities.Hotel", b =>
                {
                    b.HasOne("hoteru_be.Entities.Address", "Address")
                        .WithOne("Hotel")
                        .HasForeignKey("hoteru_be.Entities.Hotel", "IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("hoteru_be.Entities.Person", b =>
                {
                    b.HasOne("hoteru_be.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("IdHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("hoteru_be.Entities.Reservation", b =>
                {
                    b.HasOne("hoteru_be.Entities.Bill", "Bill")
                        .WithOne("Reservation")
                        .HasForeignKey("hoteru_be.Entities.Reservation", "IdBill");

                    b.HasOne("hoteru_be.Entities.Deposit", "Deposit")
                        .WithOne("Reservation")
                        .HasForeignKey("hoteru_be.Entities.Reservation", "IdDeposit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Deposit");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hoteru_be.Entities.ReservationService", b =>
                {
                    b.HasOne("hoteru_be.Entities.Reservation", "Reservation")
                        .WithMany("ReservationServices")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.Service", "Service")
                        .WithMany("ReservationServices")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("hoteru_be.Entities.Room", b =>
                {
                    b.HasOne("hoteru_be.Entities.RoomStatus", "RoomStatus")
                        .WithMany("Rooms")
                        .HasForeignKey("IdRoomStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("IdRoomType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomStatus");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("hoteru_be.Entities.User", b =>
                {
                    b.HasOne("hoteru_be.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("hoteru_be.Entities.User", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("IdUserType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("hoteru_be.Entities.Address", b =>
                {
                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("hoteru_be.Entities.Bill", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("hoteru_be.Entities.Deposit", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("hoteru_be.Entities.DepositType", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("hoteru_be.Entities.Guest", b =>
                {
                    b.Navigation("GuestReservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestStatus", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("hoteru_be.Entities.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("hoteru_be.Entities.Reservation", b =>
                {
                    b.Navigation("GuestReservations");

                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("hoteru_be.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomStatus", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hoteru_be.Entities.Service", b =>
                {
                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("hoteru_be.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
