// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hoteru_be.Context;

namespace hoteru_be.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240109193813_sdfsdf")]
    partial class sdfsdf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hoteru_be.Entities.Address", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAddress");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            IdAddress = 1,
                            City = "Warsaw",
                            Country = "Poland",
                            Postcode = "02-913",
                            Street = "Koszykowa 86"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Bill", b =>
                {
                    b.Property<int>("IdBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("IdBill");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            IdBill = 1,
                            Created = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sum = 300f
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Deposit", b =>
                {
                    b.Property<int>("IdDeposit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDepositType")
                        .HasColumnType("int");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.HasKey("IdDeposit");

                    b.HasIndex("IdDepositType");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            IdDeposit = 1,
                            IdDepositType = 1,
                            Sum = 200f
                        },
                        new
                        {
                            IdDeposit = 2,
                            IdDepositType = 1,
                            Sum = 300f
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.DepositType", b =>
                {
                    b.Property<int>("IdDepositType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDepositType");

                    b.ToTable("DepositTypes");

                    b.HasData(
                        new
                        {
                            IdDepositType = 1,
                            Title = "Card"
                        },
                        new
                        {
                            IdDepositType = 2,
                            Title = "Cash"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Guest", b =>
                {
                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdGuestStatus")
                        .HasColumnType("int");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.HasIndex("IdGuestStatus");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            IdGuestStatus = 1,
                            Passport = "FV124124",
                            TelNumber = "123123123"
                        },
                        new
                        {
                            IdPerson = 2,
                            IdGuestStatus = 1,
                            Passport = "BG121231",
                            TelNumber = "567567567"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestReservation", b =>
                {
                    b.Property<int>("IdGuestReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGuest")
                        .HasColumnType("int");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.HasKey("IdGuestReservation");

                    b.HasIndex("IdGuest");

                    b.HasIndex("IdReservation");

                    b.ToTable("GuestReservations");

                    b.HasData(
                        new
                        {
                            IdGuestReservation = 1,
                            IdGuest = 1,
                            IdReservation = 1
                        },
                        new
                        {
                            IdGuestReservation = 2,
                            IdGuest = 2,
                            IdReservation = 2
                        },
                        new
                        {
                            IdGuestReservation = 3,
                            IdGuest = 1,
                            IdReservation = 3
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestStatus", b =>
                {
                    b.Property<int>("IdGuestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGuestStatus");

                    b.ToTable("GuestStatuses");

                    b.HasData(
                        new
                        {
                            IdGuestStatus = 1,
                            Title = "VIP"
                        },
                        new
                        {
                            IdGuestStatus = 2,
                            Title = "Regular"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Hotel", b =>
                {
                    b.Property<int>("IdHotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAddress")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHotel");

                    b.HasIndex("IdAddress")
                        .IsUnique();

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            IdHotel = 1,
                            IdAddress = 1,
                            Title = "Nobu"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdHotel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.HasIndex("IdHotel");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            IdPerson = 1,
                            Email = "helli@gmail.com",
                            IdHotel = 1,
                            Name = "Gleb",
                            Surname = "Ivanov"
                        },
                        new
                        {
                            IdPerson = 2,
                            Email = "test@gmail.com",
                            IdHotel = 1,
                            Name = "Artur",
                            Surname = "Morgan"
                        },
                        new
                        {
                            IdPerson = 3,
                            Email = "password@gmail.com",
                            IdHotel = 1,
                            Name = "Mikolaj",
                            Surname = "Sluzalek"
                        },
                        new
                        {
                            IdPerson = 4,
                            Email = "marston@gmail.com",
                            IdHotel = 1,
                            Name = "Jack",
                            Surname = "Marston"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IdBill")
                        .HasColumnType("int");

                    b.Property<int?>("IdDeposit")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Out")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdBill")
                        .IsUnique()
                        .HasFilter("[IdBill] IS NOT NULL");

                    b.HasIndex("IdDeposit")
                        .IsUnique()
                        .HasFilter("[IdDeposit] IS NOT NULL");

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdUser");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            IdReservation = 1,
                            Capacity = 2,
                            Confirmed = true,
                            IdDeposit = 1,
                            IdRoom = 1,
                            IdUser = 3,
                            In = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Out = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1f
                        },
                        new
                        {
                            IdReservation = 2,
                            Capacity = 3,
                            Confirmed = true,
                            IdBill = 1,
                            IdDeposit = 2,
                            IdRoom = 2,
                            IdUser = 4,
                            In = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Out = new DateTime(2023, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 2f
                        },
                        new
                        {
                            IdReservation = 3,
                            Capacity = 2,
                            Confirmed = false,
                            IdRoom = 3,
                            IdUser = 3,
                            In = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Out = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1f
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.ReservationService", b =>
                {
                    b.Property<int>("IdReservationService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.HasKey("IdReservationService");

                    b.HasIndex("IdReservation");

                    b.HasIndex("IdService");

                    b.ToTable("ReservationServices");

                    b.HasData(
                        new
                        {
                            IdReservationService = 1,
                            Date = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdReservation = 2,
                            IdService = 1
                        },
                        new
                        {
                            IdReservationService = 2,
                            Date = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdReservation = 2,
                            IdService = 2
                        },
                        new
                        {
                            IdReservationService = 3,
                            Date = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdReservation = 2,
                            IdService = 3
                        },
                        new
                        {
                            IdReservationService = 4,
                            Date = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdReservation = 3,
                            IdService = 3
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("IdRoomStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdRoomType")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("IdRoom");

                    b.HasIndex("IdRoomStatus");

                    b.HasIndex("IdRoomType");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            IdRoom = 1,
                            Capacity = 1,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "101",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 2,
                            Capacity = 2,
                            IdRoomStatus = 1,
                            IdRoomType = 1,
                            Number = "102",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 3,
                            Capacity = 3,
                            IdRoomStatus = 2,
                            IdRoomType = 1,
                            Number = "103",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 4,
                            Capacity = 4,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "104",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 5,
                            Capacity = 5,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "105",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 6,
                            Capacity = 6,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "106",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 7,
                            Capacity = 7,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "107",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 8,
                            Capacity = 8,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "108",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 9,
                            Capacity = 9,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "109",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 10,
                            Capacity = 10,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "201",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 11,
                            Capacity = 11,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "202",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 12,
                            Capacity = 12,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "203",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 13,
                            Capacity = 13,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "204",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 14,
                            Capacity = 14,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "205",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 15,
                            Capacity = 15,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "206",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 16,
                            Capacity = 16,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "207",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 17,
                            Capacity = 17,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "208",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 18,
                            Capacity = 18,
                            IdRoomStatus = 3,
                            IdRoomType = 1,
                            Number = "209",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 19,
                            Capacity = 19,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "301",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 20,
                            Capacity = 20,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "302",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 21,
                            Capacity = 21,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "303",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 22,
                            Capacity = 22,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "304",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 23,
                            Capacity = 23,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "305",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 24,
                            Capacity = 24,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "306",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 25,
                            Capacity = 25,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "307",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 26,
                            Capacity = 26,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "308",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 27,
                            Capacity = 27,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "309",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 28,
                            Capacity = 28,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "401",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 29,
                            Capacity = 29,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "402",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 30,
                            Capacity = 30,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "403",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 31,
                            Capacity = 31,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "404",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 32,
                            Capacity = 32,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "405",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 33,
                            Capacity = 33,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "406",
                            Price = 3.5f
                        },
                        new
                        {
                            IdRoom = 34,
                            Capacity = 34,
                            IdRoomStatus = 3,
                            IdRoomType = 2,
                            Number = "407",
                            Price = 3.5f
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomStatus", b =>
                {
                    b.Property<int>("IdRoomStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoomStatus");

                    b.ToTable("RoomStatuses");

                    b.HasData(
                        new
                        {
                            IdRoomStatus = 1,
                            Title = "Out of service"
                        },
                        new
                        {
                            IdRoomStatus = 2,
                            Title = "Occupied"
                        },
                        new
                        {
                            IdRoomStatus = 3,
                            Title = "Ready"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomType", b =>
                {
                    b.Property<int>("IdRoomType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoomType");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            IdRoomType = 1,
                            Title = "Regular"
                        },
                        new
                        {
                            IdRoomType = 2,
                            Title = "Luxury"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Sum")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdService");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            IdService = 1,
                            Description = "None",
                            Sum = 355.5f,
                            Title = "Breakfast"
                        },
                        new
                        {
                            IdService = 2,
                            Description = "None",
                            Sum = 120.5f,
                            Title = "Spa"
                        },
                        new
                        {
                            IdService = 3,
                            Description = "None",
                            Sum = 248.5f,
                            Title = "Assistent"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.User", b =>
                {
                    b.Property<int>("IdPerson")
                        .HasColumnType("int");

                    b.Property<int>("IdUserType")
                        .HasColumnType("int");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerson");

                    b.HasIndex("IdUserType");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdPerson = 3,
                            IdUserType = 3,
                            LoginName = "asd",
                            Password = "asd"
                        },
                        new
                        {
                            IdPerson = 4,
                            IdUserType = 1,
                            LoginName = "qwe",
                            Password = "qwe"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.UserType", b =>
                {
                    b.Property<int>("IdUserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUserType");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            IdUserType = 1,
                            Title = "Superadmin"
                        },
                        new
                        {
                            IdUserType = 2,
                            Title = "Admin"
                        },
                        new
                        {
                            IdUserType = 3,
                            Title = "Employee"
                        });
                });

            modelBuilder.Entity("hoteru_be.Entities.Deposit", b =>
                {
                    b.HasOne("hoteru_be.Entities.DepositType", "DepositType")
                        .WithMany("Deposits")
                        .HasForeignKey("IdDepositType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepositType");
                });

            modelBuilder.Entity("hoteru_be.Entities.Guest", b =>
                {
                    b.HasOne("hoteru_be.Entities.GuestStatus", "GuestStatus")
                        .WithMany("Guests")
                        .HasForeignKey("IdGuestStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.Person", "Person")
                        .WithOne("Guest")
                        .HasForeignKey("hoteru_be.Entities.Guest", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestStatus");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestReservation", b =>
                {
                    b.HasOne("hoteru_be.Entities.Guest", "Guest")
                        .WithMany("GuestReservations")
                        .HasForeignKey("IdGuest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.Reservation", "Reservation")
                        .WithMany("GuestReservations")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("hoteru_be.Entities.Hotel", b =>
                {
                    b.HasOne("hoteru_be.Entities.Address", "Address")
                        .WithOne("Hotel")
                        .HasForeignKey("hoteru_be.Entities.Hotel", "IdAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("hoteru_be.Entities.Person", b =>
                {
                    b.HasOne("hoteru_be.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("IdHotel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("hoteru_be.Entities.Reservation", b =>
                {
                    b.HasOne("hoteru_be.Entities.Bill", "Bill")
                        .WithOne("Reservation")
                        .HasForeignKey("hoteru_be.Entities.Reservation", "IdBill");

                    b.HasOne("hoteru_be.Entities.Deposit", "Deposit")
                        .WithOne("Reservation")
                        .HasForeignKey("hoteru_be.Entities.Reservation", "IdDeposit");

                    b.HasOne("hoteru_be.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Deposit");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hoteru_be.Entities.ReservationService", b =>
                {
                    b.HasOne("hoteru_be.Entities.Reservation", "Reservation")
                        .WithMany("ReservationServices")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.Service", "Service")
                        .WithMany("ReservationServices")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("hoteru_be.Entities.Room", b =>
                {
                    b.HasOne("hoteru_be.Entities.RoomStatus", "RoomStatus")
                        .WithMany("Rooms")
                        .HasForeignKey("IdRoomStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("IdRoomType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomStatus");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("hoteru_be.Entities.User", b =>
                {
                    b.HasOne("hoteru_be.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("hoteru_be.Entities.User", "IdPerson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hoteru_be.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("IdUserType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("hoteru_be.Entities.Address", b =>
                {
                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("hoteru_be.Entities.Bill", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("hoteru_be.Entities.Deposit", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("hoteru_be.Entities.DepositType", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("hoteru_be.Entities.Guest", b =>
                {
                    b.Navigation("GuestReservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.GuestStatus", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("hoteru_be.Entities.Person", b =>
                {
                    b.Navigation("Guest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hoteru_be.Entities.Reservation", b =>
                {
                    b.Navigation("GuestReservations");

                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("hoteru_be.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomStatus", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hoteru_be.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hoteru_be.Entities.Service", b =>
                {
                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("hoteru_be.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("hoteru_be.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
